integer = @{ ASCII_DIGIT+ }

first_char = _{ ASCII_ALPHA |  "_" }
char = _{ first_char |  ASCII_DIGIT }

keywords = _{ "if" | "then" | "else" | "let" | "rec" | "fun" }

ident = @{ !( keywords ~ !char ) ~ first_char ~ char* }

atom = _{ ident | integer | "(" ~ expr ~ ")" }

bin_op = _{ add | sub | mul | div }
add = { "+" }
sub = { "-" }
mul = { "*" }
div = { "/" }

operand = _{ app_expr | atom }
equation = { operand ~ (bin_op ~ operand)* }

if_expr = { "if" ~ expr ~ "then" ~ expr ~ "else" ~ expr }
lam_expr = { "fun" ~ ident+ ~ "->" ~ expr }
let_expr = { "let" ~ ident ~ "=" ~ expr }
let_rec_expr = { "let" ~ "rec" ~ ident ~ "=" ~ expr }

app_expr = { atom ~ atom+ }

expr = _{ equation | if_expr | lam_expr }

top_level = _{ expr | let_expr | let_rec_expr  }

WHITESPACE = _ { " " }

file = _{ SOI ~ top_level ~ (";;" ~ (top_level ~ ";;")*)? ~  EOI }
