integer = @{ ASCII_DIGIT+ }

first_char = _{ ASCII_ALPHA |  "_" }
char = _{ first_char | "-" | ASCII_DIGIT }

keywords = _{ "if" | "then" | "else" }

ident = @{ !( keywords ~ !char ) ~ first_char ~ char* }

unary_minus = { "-" }
primary = _{ ident | integer | "(" ~ expr ~ ")" }

atom = _{ unary_minus? ~ primary }

bin_op = _{ add | sub | mul | div }
add = { "+" }
sub = { "-" }
mul = { "*" }
div = { "/" }

equation = { atom ~ (bin_op ~ atom)* }

// maybe make this paren
if_statement = { "if" ~ expr ~ "then" ~ expr ~ "else" ~ expr }

expr = _{ if_statement | equation }

WHITESPACE = _ { " " }

file = _{ SOI ~ expr ~ EOI }
